# Generated by Django 4.1.7 on 2024-01-04 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genreName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField(auto_now_add=True)),
                ('duration', models.PositiveIntegerField()),
                ('summary', models.CharField(max_length=200)),
                ('genreName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='work.genre')),
            ],
        ),
    ]
