# Generated by Django 4.1.7 on 2024-01-05 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_alter_movies_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='genreName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.genre'),
        ),
    ]
