# Generated by Django 4.1.7 on 2024-01-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_alter_movies_genrename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
