# Generated by Django 4.1.7 on 2024-01-05 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_alter_genre_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genreName',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genreName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.genre', to_field='genreName'),
        ),
    ]
