# Generated by Django 4.1.7 on 2024-01-05 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_alter_genre_genrename_alter_movies_genrename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='genreName',
            new_name='GenreName',
        ),
    ]
