# Generated by Django 4.1.7 on 2024-01-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_rename_genrename_movies_genrename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='movies',
            name='release_date',
            field=models.DateField(),
        ),
    ]
