# Generated by Django 4.1.7 on 2024-01-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_alter_movies_duration_alter_movies_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='duration',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='movies',
            name='release_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
